[project]
name = "sam-3d-body"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Thomash02", email = "tuomas.haapasalo02@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["sam_3d_body", "sam_3d_body.*", "tools", "tools.*"]